### ISSUE TITLE
I cant get the game to play again

### ISSUE THREAD

**Issue by cosmocochrane1** [cosmocochrane1/blackjack#2]
@pavankat 

the way ive structured my game, my "stay" button determines who the winner is and then gives back both the users cards and the dealers cards into the deck. But now im struggling to restart the game, im not sure how i would put this button into a loop. 

window.onload = function() {

	$("#fiveDollar").click(function(){
			console.log("my button works");
			user.bet();
		}
	)

	$("#hitButton").click(function(){
			console.log("hit")
			user.hit();
		}
	)

	$("#stayButton").click(function(){
			console.log("stay")
			dealer.reHit();
			compare(); 
			declareWinner();
			giveCardsBack();

		}
	)

}

**Comment by pavankat** [comment]
@cosmocochrane1 hey man you wouldn't put a button in a loop. you're trying to use the button in the same way prompt was used.

if you have the following code:

```
var dogs = [];
while (dogs.length !== 3){
   dogs.push(prompt('give me a dog name'));
}

console.log(dogs);
```

You can't replace the prompt with a button and get the same resulting program. you have to think about this differently. Perhaps like this:

```
html:
<input>
<button>submit dog name</button>

js:
var dogs = [];
$('button').on('click', function(){
   dogs.push($('input').val());

   if (dogs.length == 3){
      console.log(dogs);
   }
});
```
